import type { InterfaceLocale } from '@/i18n/locales';

const englishCopy = {
  accept: 'Accept',
  activeDuel: 'Active duel',
  almost: 'Almost',
  apiDisabled: 'Apps AV API disabled',
  attempts: 'Attempts',
  back: 'Back',
  bothReady: 'Both players are ready.',
  cancelRequest: 'Cancel request',
  challengeClosed: 'Challenge closed',
  challengeCreated: 'Challenge created. Share it with your rival.',
  challengeSubtitle: 'Create a live challenge or review an invite before joining.',
  chooseLetters: 'Choose letters',
  close: 'Close',
  code: 'Code',
  couldNotCloseTimeout: 'Could not close timed-out round',
  couldNotOpenDuel: 'The live duel could not open safely. Refresh the lobby and try again.',
  couldNotOpenNext: 'Could not open next round',
  couldNotOpenResult: 'Could not open result',
  couldNotSync: 'Could not sync round',
  countdownHelp: 'Round 1 opens when the countdown finishes.',
  createChallenge: 'Create challenge',
  creating: 'Creating…',
  decline: 'Decline',
  displayNameLabel: 'Room display name',
  displayNamePlaceholder: 'How your rival will see you',
  draw: 'Draw',
  duel: 'Duel',
  duelComplete: 'Duel complete',
  feedbackReady: 'Feedback ready',
  finalResult: 'Final result',
  findRoom: 'Find room',
  guestChallenge: 'Guest challenge',
  host: 'Host',
  inviteLabel: 'Invite link or token',
  invitePlaceholder: 'Paste invite link',
  inviteReview: 'Invite review',
  inviteShareOpened: 'Invite share opened.',
  joinChallenge: 'Join challenge',
  joinChallengeQuestion: 'Join this challenge?',
  joinHelp: 'Joining takes the open rival seat. The game starts only after both players press Ready.',
  joined: 'Joined',
  joinedChallenge: 'You joined the challenge.',
  letters: 'Letters',
  lobby: 'Lobby',
  lobbyUpdated: 'Lobby updated.',
  locked: 'Locked',
  mute: 'Mute',
  muted: 'Muted',
  nextRound: 'Next round',
  nextRoundReady: 'Next round ready',
  nice: 'Nice',
  noRematch: 'No rematch request yet.',
  offline: 'Offline',
  online: 'Online',
  onlineUnavailable: 'Online challenges are unavailable in this build',
  openFinalResult: 'Open final result',
  opening: 'Opening…',
  openingResult: 'Opening result',
  opponentAttempt: 'Opponent attempt {number}: {state}',
  ownBoard: 'Own Word Duel board',
  playAgain: 'Play again',
  ready: 'Ready',
  readyLocked: 'Ready is locked.',
  realtimeDisabled: 'Realtime disabled',
  reconnecting: 'Reconnecting',
  refresh: 'Refresh',
  refreshLobby: 'Refresh lobby',
  rematchAcceptedOpening: 'Rematch accepted. Opening the next lobby…',
  rematchAcceptedReady: 'Rematch accepted. Get ready for the next duel.',
  rematchCancelled: 'The rematch request was cancelled.',
  rematchDeclined: 'The rematch was declined.',
  rematchExpired: 'The rematch request expired.',
  rematchSent: 'Rematch sent. Your rival can accept it from their result screen.',
  rematchStatus: 'Rematch {status}.',
  rematchUpdated: 'Rematch status updated.',
  requestRematch: 'Request rematch',
  requestRematchHelp: 'Request a new duel with the same rival.',
  resolving: 'Resolving',
  reviewBeforeJoin: 'Review the challenge before joining.',
  reviewInvite: 'Review invite',
  rival: 'Rival',
  rivalReady: 'Rival ready',
  rivalRequestedRematch: 'Your rival requested a rematch.',
  rivalSubmitted: 'Rival submitted',
  rivalWon: 'Rival won',
  roomCode: 'Room code',
  roomCodeInvalid: 'Enter the eight-character room code.',
  roomName: 'Your room name',
  roomNameHelp: 'Used only for this challenge. No account is required.',
  roomNameInvalid: 'Enter the name your rival will see.',
  roomNameTooLong: 'Use a room name with 32 characters or fewer.',
  roomNameUnsupported: 'Remove unsupported characters from your room name.',
  round: 'Round',
  roundChanged: 'Round changed',
  roundReady: 'Round 1 is ready.',
  roundReadyTitle: 'Round 1 is ready',
  roundResolving: 'Round still resolving',
  roundTimedOut: 'Round timed out',
  runtimeDescription: 'DuelWords stays offline unless both the Apps AV API and safe realtime configuration are enabled.',
  safeRealtimeUnavailable: 'Safe realtime is not ready',
  shareInvite: 'Share invite',
  shareResult: 'Share result',
  side: 'Side',
  slowDown: 'Slow down',
  solved: 'Solved',
  starting: 'Starting',
  submitted: 'Submitted',
  submitting: 'Submitting',
  syncRound: 'Sync round',
  target: 'Target: {word}',
  timedOut: 'Timed out',
  time: 'Time',
  tryAgain: 'Try again',
  unavailable: 'Unavailable',
  unsupportedInvite: 'Use a DuelWords AV invite link.',
  validInviteRequired: 'Enter a valid invite link or token.',
  waiting: 'Waiting',
  waitingForAnswer: 'Waiting for your rival to answer.',
  waitingForRival: 'Waiting for rival',
  waitingRound: 'Waiting for round 1.',
  wordLength: '{count} letters',
  you: 'You',
  youWon: 'You won',
  yourFinalBoard: 'Your final board',
  yourTurn: 'Your turn',
  actionUnavailable: 'That action is not available right now. Try again.',
  safeRealtimeRequired: 'Safe realtime is required for connected play.',
  rivalFinalBoard: 'Rival final board',
} as const;

export type PublicDuelCopyKey = keyof typeof englishCopy;

const spanishCopy: Record<PublicDuelCopyKey, string> = {
  ...englishCopy,
  accept: 'Aceptar', activeDuel: 'Duelo activo', almost: 'Casi', apiDisabled: 'API de Apps AV desactivada', attempts: 'Intentos', back: 'Volver', bothReady: 'Ambos jugadores están listos.', cancelRequest: 'Cancelar solicitud', challengeClosed: 'Reto cerrado', challengeCreated: 'Reto creado. Compártelo con tu rival.', challengeSubtitle: 'Crea un reto en directo o revisa una invitación antes de unirte.', chooseLetters: 'Elige letras', close: 'Cerrar', code: 'Código', countdownHelp: 'La ronda 1 se abre al terminar la cuenta atrás.', createChallenge: 'Crear reto', creating: 'Creando…', decline: 'Rechazar', displayNameLabel: 'Nombre en la sala', displayNamePlaceholder: 'Cómo te verá tu rival', draw: 'Empate', duel: 'Duelo', duelComplete: 'Duelo terminado', feedbackReady: 'Pistas disponibles', finalResult: 'Resultado final', findRoom: 'Buscar sala', guestChallenge: 'Reto como invitado', host: 'Anfitrión', inviteLabel: 'Enlace o token de invitación', invitePlaceholder: 'Pega el enlace de invitación', inviteReview: 'Revisar invitación', inviteShareOpened: 'Se abrió el menú para compartir.', joinChallenge: 'Unirse al reto', joinChallengeQuestion: '¿Unirte a este reto?', joinHelp: 'Al unirte ocuparás la plaza rival. La partida solo empieza cuando ambos pulsan Listo.', joined: 'Dentro', joinedChallenge: 'Te has unido al reto.', letters: 'Letras', lobby: 'Sala', lobbyUpdated: 'Sala actualizada.', locked: 'Bloqueado', mute: 'Silenciar', muted: 'Silenciado', nextRound: 'Siguiente ronda', nextRoundReady: 'Siguiente ronda lista', nice: 'Bien', noRematch: 'Todavía no hay solicitud de revancha.', offline: 'Sin conexión', online: 'En línea', onlineUnavailable: 'Los retos online no están disponibles en esta compilación', openFinalResult: 'Abrir resultado final', opening: 'Abriendo…', openingResult: 'Abriendo resultado', opponentAttempt: 'Intento rival {number}: {state}', ownBoard: 'Tu tablero de Word Duel', playAgain: 'Jugar de nuevo', ready: 'Listo', readyLocked: 'Listo queda bloqueado.', realtimeDisabled: 'Realtime desactivado', reconnecting: 'Reconectando', refresh: 'Actualizar', refreshLobby: 'Actualizar sala', rematchAcceptedOpening: 'Revancha aceptada. Abriendo la siguiente sala…', rematchAcceptedReady: 'Revancha aceptada. Prepárate para el siguiente duelo.', rematchCancelled: 'La solicitud de revancha se canceló.', rematchDeclined: 'La revancha fue rechazada.', rematchExpired: 'La solicitud de revancha caducó.', rematchSent: 'Revancha enviada. Tu rival puede aceptarla desde su resultado.', rematchStatus: 'Revancha: {status}.', rematchUpdated: 'Estado de revancha actualizado.', requestRematch: 'Pedir revancha', requestRematchHelp: 'Pide otro duelo con el mismo rival.', resolving: 'Resolviendo', reviewBeforeJoin: 'Revisa el reto antes de unirte.', reviewInvite: 'Revisar invitación', rival: 'Rival', rivalReady: 'Rival listo', rivalRequestedRematch: 'Tu rival ha pedido una revancha.', rivalSubmitted: 'El rival envió su palabra', rivalWon: 'Ganó tu rival', roomCode: 'Código de sala', roomCodeInvalid: 'Introduce el código de sala de ocho caracteres.', roomName: 'Tu nombre en la sala', roomNameHelp: 'Solo se usa para este reto. No necesitas cuenta.', roomNameInvalid: 'Introduce el nombre que verá tu rival.', roomNameTooLong: 'Usa un nombre de 32 caracteres o menos.', roomNameUnsupported: 'Elimina los caracteres no admitidos.', round: 'Ronda', roundChanged: 'La ronda cambió', roundReady: 'La ronda 1 está lista.', roundReadyTitle: 'La ronda 1 está lista', roundResolving: 'La ronda sigue resolviéndose', roundTimedOut: 'Tiempo de ronda agotado', runtimeDescription: 'DuelWords permanece sin conexión salvo que estén habilitadas la API de Apps AV y la configuración segura de realtime.', shareInvite: 'Compartir invitación', shareResult: 'Compartir resultado', side: 'Lado', slowDown: 'Más despacio', solved: 'Resuelto', starting: 'Empezando', submitted: 'Enviado', submitting: 'Enviando', syncRound: 'Sincronizar ronda', target: 'Palabra: {word}', timedOut: 'Sin tiempo', time: 'Tiempo', tryAgain: 'Inténtalo de nuevo', unavailable: 'No disponible', unsupportedInvite: 'Usa un enlace de invitación de DuelWords AV.', validInviteRequired: 'Introduce un enlace o token válido.', waiting: 'Esperando', waitingForAnswer: 'Esperando la respuesta de tu rival.', waitingForRival: 'Esperando rival', waitingRound: 'Esperando la ronda 1.', wordLength: '{count} letras', you: 'Tú', youWon: 'Has ganado', yourFinalBoard: 'Tu tablero final', yourTurn: 'Tu turno', actionUnavailable: 'Esa acción no está disponible ahora. Inténtalo de nuevo.', safeRealtimeRequired: 'Se necesita realtime seguro para jugar online.', rivalFinalBoard: 'Tablero final del rival',
};

const catalanCopy: Record<PublicDuelCopyKey, string> = {
  ...spanishCopy,
  accept: 'Acceptar', activeDuel: 'Duel actiu', attempts: 'Intents', back: 'Tornar', bothReady: 'Tots dos jugadors estan preparats.', cancelRequest: 'Cancel·lar sol·licitud', challengeClosed: 'Repte tancat', challengeCreated: 'Repte creat. Comparteix-lo amb el teu rival.', challengeSubtitle: 'Crea un repte en directe o revisa una invitació abans d’unir-t’hi.', chooseLetters: 'Tria lletres', close: 'Tancar', code: 'Codi', createChallenge: 'Crear repte', creating: 'Creant…', decline: 'Rebutjar', displayNameLabel: 'Nom a la sala', displayNamePlaceholder: 'Com et veurà el teu rival', draw: 'Empat', duel: 'Duel', duelComplete: 'Duel acabat', finalResult: 'Resultat final', findRoom: 'Cercar sala', guestChallenge: 'Repte com a convidat', host: 'Amfitrió', inviteLabel: 'Enllaç o token d’invitació', invitePlaceholder: 'Enganxa l’enllaç d’invitació', inviteReview: 'Revisar invitació', joinChallenge: 'Unir-se al repte', joinChallengeQuestion: 'Vols unir-te a aquest repte?', joined: 'Dins', letters: 'Lletres', lobby: 'Sala', mute: 'Silenciar', muted: 'Silenciat', nextRound: 'Ronda següent', online: 'En línia', offline: 'Sense connexió', openFinalResult: 'Obrir resultat final', playAgain: 'Tornar a jugar', ready: 'Preparat', refresh: 'Actualitzar', refreshLobby: 'Actualitzar sala', requestRematch: 'Demanar revenja', reviewInvite: 'Revisar invitació', rival: 'Rival', roomCode: 'Codi de sala', roomName: 'El teu nom a la sala', round: 'Ronda', shareInvite: 'Compartir invitació', shareResult: 'Compartir resultat', side: 'Costat', solved: 'Resolt', starting: 'Començant', syncRound: 'Sincronitzar ronda', target: 'Paraula: {word}', time: 'Temps', waiting: 'Esperant', waitingForRival: 'Esperant rival', wordLength: '{count} lletres', you: 'Tu', youWon: 'Has guanyat', yourTurn: 'El teu torn',
};

const frenchCopy: Record<PublicDuelCopyKey, string> = {
  ...englishCopy,
  accept: 'Accepter', activeDuel: 'Duel actif', attempts: 'Essais', back: 'Retour', bothReady: 'Les deux joueurs sont prêts.', cancelRequest: 'Annuler la demande', challengeClosed: 'Défi terminé', challengeCreated: 'Défi créé. Partagez-le avec votre rival.', challengeSubtitle: 'Créez un défi en direct ou vérifiez une invitation avant de rejoindre.', chooseLetters: 'Choisissez les lettres', close: 'Fermer', code: 'Code', createChallenge: 'Créer le défi', creating: 'Création…', decline: 'Refuser', displayNameLabel: 'Nom dans la salle', displayNamePlaceholder: 'Le nom vu par votre rival', draw: 'Égalité', duel: 'Duel', duelComplete: 'Duel terminé', finalResult: 'Résultat final', findRoom: 'Trouver la salle', guestChallenge: 'Défi invité', host: 'Hôte', inviteLabel: 'Lien ou jeton d’invitation', invitePlaceholder: 'Collez le lien d’invitation', inviteReview: 'Vérifier l’invitation', joinChallenge: 'Rejoindre le défi', joinChallengeQuestion: 'Rejoindre ce défi ?', joined: 'Rejoint', letters: 'Lettres', lobby: 'Salon', mute: 'Couper le son', muted: 'Son coupé', nextRound: 'Manche suivante', offline: 'Hors ligne', online: 'En ligne', openFinalResult: 'Ouvrir le résultat final', playAgain: 'Rejouer', ready: 'Prêt', reconnecting: 'Reconnexion', refresh: 'Actualiser', refreshLobby: 'Actualiser le salon', requestRematch: 'Demander une revanche', reviewInvite: 'Vérifier l’invitation', rival: 'Rival', roomCode: 'Code de salle', roomName: 'Votre nom dans la salle', round: 'Manche', shareInvite: 'Partager l’invitation', shareResult: 'Partager le résultat', side: 'Côté', solved: 'Résolu', starting: 'Démarrage', syncRound: 'Synchroniser', target: 'Mot : {word}', timedOut: 'Temps écoulé', time: 'Temps', waiting: 'En attente', waitingForRival: 'En attente du rival', wordLength: '{count} lettres', you: 'Vous', youWon: 'Vous avez gagné', yourTurn: 'À vous',
};

const germanCopy: Record<PublicDuelCopyKey, string> = {
  ...englishCopy,
  accept: 'Annehmen', activeDuel: 'Aktives Duell', attempts: 'Versuche', back: 'Zurück', bothReady: 'Beide Spieler sind bereit.', cancelRequest: 'Anfrage abbrechen', challengeClosed: 'Herausforderung beendet', challengeCreated: 'Herausforderung erstellt. Teile sie mit deinem Rivalen.', challengeSubtitle: 'Erstelle eine Live-Herausforderung oder prüfe eine Einladung vor dem Beitritt.', chooseLetters: 'Buchstaben wählen', close: 'Schließen', code: 'Code', createChallenge: 'Herausforderung erstellen', creating: 'Wird erstellt…', decline: 'Ablehnen', displayNameLabel: 'Name im Raum', displayNamePlaceholder: 'So sieht dich dein Rivale', draw: 'Unentschieden', duel: 'Duell', duelComplete: 'Duell beendet', finalResult: 'Endergebnis', findRoom: 'Raum finden', guestChallenge: 'Gast-Herausforderung', host: 'Gastgeber', inviteLabel: 'Einladungslink oder Token', invitePlaceholder: 'Einladungslink einfügen', inviteReview: 'Einladung prüfen', joinChallenge: 'Herausforderung beitreten', joinChallengeQuestion: 'Dieser Herausforderung beitreten?', joined: 'Beigetreten', letters: 'Buchstaben', lobby: 'Lobby', mute: 'Stumm', muted: 'Stummgeschaltet', nextRound: 'Nächste Runde', offline: 'Offline', online: 'Online', openFinalResult: 'Endergebnis öffnen', playAgain: 'Noch einmal spielen', ready: 'Bereit', reconnecting: 'Verbindung wird hergestellt', refresh: 'Aktualisieren', refreshLobby: 'Lobby aktualisieren', requestRematch: 'Revanche anfragen', reviewInvite: 'Einladung prüfen', rival: 'Rivale', roomCode: 'Raumcode', roomName: 'Dein Name im Raum', round: 'Runde', shareInvite: 'Einladung teilen', shareResult: 'Ergebnis teilen', side: 'Seite', solved: 'Gelöst', starting: 'Startet', syncRound: 'Runde synchronisieren', target: 'Wort: {word}', timedOut: 'Zeit abgelaufen', time: 'Zeit', waiting: 'Warten', waitingForRival: 'Auf Rivalen warten', wordLength: '{count} Buchstaben', you: 'Du', youWon: 'Du hast gewonnen', yourTurn: 'Du bist dran',
};

const publicDuelCopy: Record<InterfaceLocale, Record<PublicDuelCopyKey, string>> = {
  ca: catalanCopy,
  de: germanCopy,
  en: englishCopy,
  es: spanishCopy,
  fr: frenchCopy,
};

export function publicDuelT(
  locale: InterfaceLocale,
  key: PublicDuelCopyKey,
  values: Record<string, string | number> = {},
): string {
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    publicDuelCopy[locale][key],
  );
}
