#import <React/RCTViewManager.h>

@interface RCT_EXTERN_MODULE(DuelWordsSimulatorUITestRuntime, NSObject)
@end

@interface RCT_EXTERN_MODULE(DuelWordsSharedAppleViewManager, RCTViewManager)
RCT_EXPORT_VIEW_PROPERTY(surface, NSString)
RCT_EXPORT_VIEW_PROPERTY(selectedTab, NSString)
RCT_EXPORT_VIEW_PROPERTY(interfaceLocale, NSString)
RCT_EXPORT_VIEW_PROPERTY(appearance, NSString)
RCT_EXPORT_VIEW_PROPERTY(aviDifficulty, NSString)
RCT_EXPORT_VIEW_PROPERTY(accountAvailable, BOOL)
RCT_EXPORT_VIEW_PROPERTY(signedIn, BOOL)
RCT_EXPORT_VIEW_PROPERTY(displayName, NSString)
RCT_EXPORT_VIEW_PROPERTY(deletionBlockersJSON, NSString)
RCT_EXPORT_VIEW_PROPERTY(deletionBusy, BOOL)
RCT_EXPORT_VIEW_PROPERTY(deletionCanFinalize, BOOL)
RCT_EXPORT_VIEW_PROPERTY(deletionError, NSString)
RCT_EXPORT_VIEW_PROPERTY(deletionStatus, NSString)
RCT_EXPORT_VIEW_PROPERTY(deletionWarningsJSON, NSString)
RCT_EXPORT_VIEW_PROPERTY(email, NSString)
RCT_EXPORT_VIEW_PROPERTY(planTier, NSString)
RCT_EXPORT_VIEW_PROPERTY(playerDisplayName, NSString)
RCT_EXPORT_VIEW_PROPERTY(activeProvider, NSString)
RCT_EXPORT_VIEW_PROPERTY(authError, NSString)
RCT_EXPORT_VIEW_PROPERTY(authInitiallyPresented, BOOL)
RCT_EXPORT_VIEW_PROPERTY(hapticsEnabled, BOOL)
RCT_EXPORT_VIEW_PROPERTY(gameLanguage, NSString)
RCT_EXPORT_VIEW_PROPERTY(subscriptionBusy, BOOL)
RCT_EXPORT_VIEW_PROPERTY(subscriptionError, NSString)
RCT_EXPORT_VIEW_PROPERTY(subscriptionPrice, NSString)
RCT_EXPORT_VIEW_PROPERTY(subscriptionState, NSString)
RCT_EXPORT_VIEW_PROPERTY(onAction, RCTBubblingEventBlock)
@end
