# frozen_string_literal: true

require 'fileutils'
require 'xcodeproj'

repo_root = File.expand_path(ARGV.fetch(0))
ios_root = File.join(repo_root, 'ios')
project_path = File.join(ios_root, 'DuelWordsAV.xcodeproj')
config_root = File.join(ios_root, 'Config')

abort('DuelWordsAV.xcodeproj is missing; run Expo prebuild first.') unless File.directory?(project_path)

FileUtils.mkdir_p(config_root)

wrappers = {
  'Debug' => 'DuelWordsAV.Debug.xcconfig',
  'Release' => 'DuelWordsAV.Release.xcconfig'
}

wrappers.each do |configuration, filename|
  pods_name = "Pods-DuelWordsAV.#{configuration.downcase}.xcconfig"
  File.write(
    File.join(config_root, filename),
    <<~XCCONFIG
      // GENERATED by scripts/ios/configure-local-xcconfig.rb
      // Do not edit or commit this file.
      #include? "../Pods/Target Support Files/Pods-DuelWordsAV/#{pods_name}"
      #include "Local.xcconfig"
    XCCONFIG
  )
end

project = Xcodeproj::Project.open(project_path)
target = project.targets.find { |candidate| candidate.name == 'DuelWordsAV' }
abort('DuelWordsAV Xcode target is missing.') unless target

config_group = project.main_group.find_subpath('Config', true)
config_group.set_source_tree('<group>')
config_group.set_path('Config')

references = wrappers.transform_values do |filename|
  config_group.files.find { |file| file.path == filename } || config_group.new_file(filename)
end

target.build_configurations.each do |configuration|
  reference = references[configuration.name]
  configuration.base_configuration_reference = reference if reference
end

project.save
