#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
workspace_root="$(cd "$repo_root/../.." && pwd)"
suite_root="${AVALSYS_SUITE_DIR:-$workspace_root/private/avalsys-suite}"
output_path="$repo_root/ios/Config/Local.xcconfig"
xcode_env_path="$repo_root/ios/.xcode.env.local"
env_name=""

usage() {
  cat <<'USAGE'
Usage:
  scripts/ios/generate-local-xcconfig.sh --env dev|preview|prod

Generates the ignored Xcode build environment used by Expo's JavaScript bundle
phase. Infisical remains read-only; no value is printed or committed. Production
keeps connected Challenge and Convex fail-closed while Account AV stays enabled.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --env)
      env_name="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$env_name" in
  dev)
    profile="local"
    build_variant="development"
    bundle_identifier="com.avalsys.duelwordsav.dev"
    api_base_url="https://api-account-av-preview.avalsys.com"
    api_disabled="false"
    realtime_disabled="false"
    sentry_environment="debug"
    ;;
  preview)
    profile="local"
    build_variant="release"
    bundle_identifier="com.avalsys.duelwordsav"
    api_base_url="https://api-account-av-preview.avalsys.com"
    api_disabled="false"
    realtime_disabled="false"
    sentry_environment="preview"
    ;;
  prod)
    profile="production"
    build_variant="release"
    bundle_identifier="com.avalsys.duelwordsav"
    api_base_url="https://api-account-av.avalsys.com"
    api_disabled="true"
    realtime_disabled="true"
    sentry_environment="production"
    ;;
  *)
    echo "--env must be dev, preview, or prod." >&2
    exit 2
    ;;
esac

varlock_bin="$suite_root/node_modules/.bin/varlock"
bootstrap="$suite_root/scripts/resolve-infisical-bootstrap-env.sh"
if [ ! -x "$varlock_bin" ] || [ ! -x "$bootstrap" ]; then
  echo "Private read-only Varlock/Infisical tooling is unavailable." >&2
  exit 1
fi

eval "$("$bootstrap" "$profile")"

read_account_publishable_key() {
  local value="${ACCOUNTAV_PUBLISHABLE_KEY:-${VITE_ACCOUNTAV_PUBLISHABLE_KEY:-}}"
  if [ -n "$value" ]; then
    printf '%s' "$value"
    return
  fi
  "$varlock_bin" printenv --path "$suite_root/apps/account-av" VITE_ACCOUNTAV_PUBLISHABLE_KEY
}

read_service_value() {
  local name="$1"
  local value="${!name:-}"
  if [ -n "$value" ]; then
    printf '%s' "$value"
    return
  fi
  "$varlock_bin" printenv --path "$suite_root/services/api" "$name" 2>/dev/null || true
}

publishable_key="$(read_account_publishable_key)"
convex_url="$(read_service_value DUELWORDSAV_CONVEX_URL)"
sentry_dsn="$(read_service_value DUELWORDSAV_IOS_SENTRY_DSN)"

case "$publishable_key" in
  pk_test_*|pk_live_*) ;;
  *) echo "ACCOUNTAV_PUBLISHABLE_KEY is missing or malformed for $env_name." >&2; exit 1 ;;
esac
if [ "$env_name" = "prod" ] && [[ "$publishable_key" != pk_live_* ]]; then
  echo "ACCOUNTAV_PUBLISHABLE_KEY must use pk_live_ for prod." >&2
  exit 1
fi
case "$convex_url" in
  https://*.convex.cloud) ;;
  *) echo "DUELWORDSAV_CONVEX_URL must resolve to a Convex cloud URL for $env_name." >&2; exit 1 ;;
esac

escape_xcconfig_url() {
  printf '%s' "$1" | sed 's#/#$(XCCONFIG_SLASH)#g'
}

umask 077
mkdir -p "$(dirname "$output_path")"
{
  printf '%s\n' '// GENERATED by scripts/ios/generate-local-xcconfig.sh'
  printf '%s\n' '// Do not edit, print, or commit this file.'
  printf '%s\n' 'XCCONFIG_SLASH = /'
  printf 'DUELWORDSAV_RUNTIME_ENVIRONMENT = %s\n' "$env_name"
  printf 'DUELWORDSAV_IOS_BUILD_VARIANT = %s\n' "$build_variant"
  printf 'PRODUCT_BUNDLE_IDENTIFIER = %s\n' "$bundle_identifier"
  printf 'ACCOUNTAV_PUBLISHABLE_KEY = %s\n' "$publishable_key"
  printf '%s\n' 'ACCOUNTAV_KEYCHAIN_SERVICE = com.avalsys.duelwordsav.account'
  printf 'ACCOUNTAV_KEYCHAIN_ACCESS_GROUP = 935PM55U6R.%s\n' "$bundle_identifier"
  printf 'EXPO_PUBLIC_DUELWORDSAV_API_BASE_URL = %s\n' "$(escape_xcconfig_url "$api_base_url")"
  printf 'EXPO_PUBLIC_DUELWORDSAV_API_DISABLED = %s\n' "$api_disabled"
  printf 'EXPO_PUBLIC_DUELWORDSAV_CONVEX_URL = %s\n' "$(escape_xcconfig_url "$convex_url")"
  printf 'EXPO_PUBLIC_DUELWORDSAV_CONVEX_REALTIME_DISABLED = %s\n' "$realtime_disabled"
  printf 'EXPO_PUBLIC_DUELWORDSAV_SENTRY_ENVIRONMENT = %s\n' "$sentry_environment"
  if [ -n "$sentry_dsn" ]; then
    printf 'EXPO_PUBLIC_DUELWORDSAV_SENTRY_DSN = %s\n' "$(escape_xcconfig_url "$sentry_dsn")"
  fi
} > "$output_path"

managed_start='# BEGIN DUELWORDSAV MANAGED RUNTIME'
managed_end='# END DUELWORDSAV MANAGED RUNTIME'
preserved_env="$(mktemp)"
generated_env="$(mktemp)"
trap 'rm -f "$preserved_env" "$generated_env"' EXIT

if [ -f "$xcode_env_path" ]; then
  awk -v start="$managed_start" -v end="$managed_end" '
    $0 == start { managed = 1; next }
    $0 == end { managed = 0; next }
    !managed { print }
  ' "$xcode_env_path" > "$preserved_env"
fi

shell_export() {
  local name="$1"
  local value="$2"
  printf 'export %s=%q\n' "$name" "$value"
}

{
  cat "$preserved_env"
  printf '%s\n' "$managed_start"
  shell_export DUELWORDSAV_IOS_BUILD_VARIANT "$build_variant"
  shell_export ACCOUNTAV_PUBLISHABLE_KEY "$publishable_key"
  shell_export ACCOUNTAV_KEYCHAIN_SERVICE 'com.avalsys.duelwordsav.account'
  shell_export ACCOUNTAV_KEYCHAIN_ACCESS_GROUP "935PM55U6R.$bundle_identifier"
  shell_export EXPO_PUBLIC_DUELWORDSAV_API_BASE_URL "$api_base_url"
  shell_export EXPO_PUBLIC_DUELWORDSAV_API_DISABLED "$api_disabled"
  shell_export EXPO_PUBLIC_DUELWORDSAV_CONVEX_URL "$convex_url"
  shell_export EXPO_PUBLIC_DUELWORDSAV_CONVEX_REALTIME_DISABLED "$realtime_disabled"
  shell_export EXPO_PUBLIC_DUELWORDSAV_SENTRY_ENVIRONMENT "$sentry_environment"
  if [ -n "$sentry_dsn" ]; then
    shell_export EXPO_PUBLIC_DUELWORDSAV_SENTRY_DSN "$sentry_dsn"
  fi
  printf '%s\n' "$managed_end"
} > "$generated_env"
mv "$generated_env" "$xcode_env_path"
chmod 600 "$xcode_env_path"

configure_xcode_project() {
  local configurator="$repo_root/scripts/ios/configure-local-xcconfig.rb"
  if ruby -e "require 'xcodeproj'" >/dev/null 2>&1; then
    ruby "$configurator" "$repo_root"
    return
  fi

  local pod_bin
  local pod_gem_home
  pod_bin="$(command -v pod || true)"
  pod_gem_home="$(sed -n 's/^GEM_HOME="\([^"]*\)".*/\1/p' "$pod_bin" 2>/dev/null | head -n 1)"
  if [ -n "$pod_gem_home" ] && GEM_HOME="$pod_gem_home" ruby -e "require 'xcodeproj'" >/dev/null 2>&1; then
    GEM_HOME="$pod_gem_home" ruby "$configurator" "$repo_root"
    return
  fi

  echo "The CocoaPods xcodeproj runtime is unavailable." >&2
  return 1
}

configure_xcode_project

echo "Generated ignored iOS runtime config for $env_name."
